- name: absent /etc/my.cnf
  sudo: yes
  file:
    path: /etc/my.cnf
    state: absent

- name: install packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - "@Development tools"
    - cmake

- name: create mysql group
  sudo: yes
  group:
    name: "{{ mysql_group }}"
    system: yes
    state: present

- name: create mysql user
  sudo: yes
  user:
    name: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    createhome: no
    system: yes
    state: present

- name: create mysql directory
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: 0755
  with_items:
    - "{{ mysql_basedir }}"
    - "{{ mysql_datadir }}"

- name: clone mysql-build
  sudo: yes
  git:
    repo: https://github.com/kamipo/mysql-build.git
    dest: "{{ mysql_build_checkout_dest }}"
    version: "{{ mysql_build_version }}"
    accept_hostkey: yes

- name: build mysql
  sudo: yes
  command: |
    {{ mysql_build_checkout_dest }}/bin/mysql-build {{ mysql_version }} {{ mysql_basedir }} {{ mysql_plugin }}
    creates={{ mysql_basedir }}/README

- name: fix directory permission
  sudo: yes
  file:
    path: "{{ item }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ mysql_basedir }}"
    - "{{ mysql_datadir }}"

- name: link rc script
  sudo: yes
  file:
    src: "{{ mysql_basedir }}/support-files/mysql.server"
    dest: "/etc/init.d/{{ mysql_rc_script }}"
    state: link

- name: create {{ mysql_basedir }}/etc directory
  sudo: yes
  file:
    path: "{{ mysql_basedir }}/etc"
    state: directory

- name: configure {{ mysql_basedir }}/etc/my.cnf
  sudo: yes
  ini_file:
    dest: "{{ mysql_basedir }}/etc/my.cnf"
    option: "{{ item.option }}"
    section: "{{ item.section }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ mysql_config }}"
    - "{{ mysql_append_config }}"

- name: ensure stopped service
  sudo: yes
  service:
    name: "{{ mysql_rc_script }}"
    state: stopped
  ignore_errors: yes

- name: run mysql_install_db
  sudo: yes
  command: |
    ./scripts/mysql_install_db --user={{ mysql_user }}
    creates={{ mysql_basedir }}/my-new.cnf
    chdir={{ mysql_basedir }}

- name: ensure started service
  sudo: yes
  service:
    name: "{{ mysql_rc_script }}"
    enabled: yes
    state: started
