---
galaxy_info:
  author: xcezx
  description: install and configuration php
  license: BSD
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 6
  categories:
    - development
    - web
dependencies: []
