- hosts: all
  roles:
    - { role: goozbach.EPEL, sudo: yes }

- hosts: server
  roles:
    - { role: xcezx.httpd, sudo: yes }
    - { role: xcezx.php, sudo: yes }
    - { role: xcezx.mysql, sudo: yes }

- hosts: server
  tasks:
    - name: install MySQL-python
      sudo: yes
      yum: { name: MySQL-python, state: present }
