# for xcezx.httpd
httpd_install_packages:
  - { name: "httpd", enablerepo: ~ }
httpd_prefork_StartServers:        "{{ ansible_processor_cores }}"
httpd_prefork_MinSpareServers:     "{{ ansible_processor_cores }}"
httpd_prefork_MaxSpareServers:     "{{ ansible_processor_cores }}"
httpd_prefork_ServerLimit:         "{{ ansible_processor_cores }}"
httpd_prefork_MaxClients:          "{{ ansible_processor_cores }}"
httpd_prefork_MaxRequestsPerChild: 64

# for xcezx.php
php_install_packages:
  - { name: php-common, enablerepo: ~ }
php_additional_install_packages:
  - { name: php-xml, enablerepo: ~ }
  - { name: php-bcmath, enablerepo: ~ }
  - { name: php-mbstring, enablerepo: ~ }
  - { name: php-gd, enablerepo: ~ }
  - { name: php-pecl-apc, enablerepo: ~ }
  - { name: php-mysql, enablerepo: ~ }
  - { name: php-pdo, enablerepo: ~ }
php_config:
  - { section: "local", option: "date.timezone", value: "Asia/Tokyo" }

# for xcezx.mysql
mysql_root_password: "xZ5g3MZD"
mysql_append_config:
  - { section: "mysqld", option: "skip-character-set-client-handshake", value: "ON" }
  - { section: "mysql", option: "default-character-set", value: "utf8" }

# for xcezx.zabbix-server
zabbix_server_DBHost: "10.0.0.10"
zabbix_server_DBName: "zabbix"
zabbix_server_DBPassword: "zabbix"
zabbix_server_DBUser: "zabbix"
zabbix_server_DBPort: "3306"
